services:
  adminer:
    image: adminer:latest
    container_name: todo_adminer_dev
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: todo_db_dev
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-tododb}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    container_name: todo_server_dev
    build: ./server
    depends_on:
      - db
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      DATABASE_URL: postgresql://${DB_USER:-user}:${DB_PASSWORD:-password}@db:5432/${DB_NAME:-tododb}?schema=public
      NODE_ENV: development
      PORT: ${APP_PORT:-3000}
      JWT_SECRET: ${JWT_SECRET:-YourSuperSecretKey123!ChangeMe!}
      DEBUG: express:*
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./server
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  client:
    container_name: todo_client_dev
    build: ./client
    depends_on:
      - app
    ports:
      - "${CLIENT_PORT:-5173}:5173"
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./client
          target: /usr/src/app-client
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
