services:
  adminer:
    image: adminer:latest
    container_name: todo_adminer_dev
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: todo_db_dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file: ".env"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    container_name: todo_server_dev
    build: ./server
    depends_on:
      - db
    env_file: ".env"
    ports:
      - "${APP_PORT}:3000"
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./server
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  client:
    container_name: todo_client_dev
    build: ./client
    depends_on:
      - app
    env_file: ".env"
    ports:
      - "${CLIENT_PORT}:5173"
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./client
          target: /usr/src/app-client
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
